export type FontOption = {
  id: string;
  label: string;
  sub: string;
  css: string;
};

export const FONTS: FontOption[] = [
  { id: "mashanzheng", label: "行楷 Ma Shan Zheng", sub: "flowing running script", css: "'Ma Shan Zheng', serif" },
  { id: "zhimangxing", label: "草书 Zhi Mang Xing", sub: "wild cursive", css: "'Zhi Mang Xing', serif" },
  { id: "longcang", label: "行草 Long Cang", sub: "loose brush hand", css: "'Long Cang', serif" },
  { id: "notoserifsc", label: "楷体 Noto Serif SC", sub: "classical regular script", css: "'Noto Serif SC', serif" },
  { id: "zcool", label: "宋刻 ZCOOL XiaoWei", sub: "carved song style", css: "'ZCOOL XiaoWei', serif" },
  { id: "cormorant", label: "Cormorant", sub: "latin didone serif", css: "'Cormorant Garamond', serif" },
  { id: "dancing", label: "Dancing Script", sub: "latin cursive hand", css: "'Dancing Script', cursive" },
];

export type Preset = { label: string; text: string; note: string; lang: "zh" | "en" };

export const PRESETS: Preset[] = [
  // ——— 古典诗词 · classical ———
  { label: "静夜思", text: "床前明月光\n疑是地上霜", note: "李白 · Li Bai", lang: "zh" },
  { label: "登鹳雀楼", text: "白日依山尽\n黄河入海流", note: "王之涣 · Wang Zhihuan", lang: "zh" },
  { label: "兰亭序", text: "永和九年\n岁在癸丑", note: "王羲之 · Wang Xizhi", lang: "zh" },
  { label: "春晓", text: "春眠不觉晓\n处处闻啼鸟", note: "孟浩然 · Meng Haoran", lang: "zh" },
  { label: "相思", text: "红豆生南国\n春来发几枝", note: "王维 · Wang Wei", lang: "zh" },
  { label: "鹿柴", text: "空山不见人\n但闻人语响", note: "王维 · Wang Wei", lang: "zh" },
  { label: "山居秋暝", text: "明月松间照\n清泉石上流", note: "王维 · Wang Wei", lang: "zh" },
  { label: "送元二使安西", text: "劝君更尽一杯酒\n西出阳关无故人", note: "王维 · Wang Wei", lang: "zh" },
  { label: "望庐山瀑布", text: "飞流直下三千尺\n疑是银河落九天", note: "李白 · Li Bai", lang: "zh" },
  { label: "早发白帝城", text: "两岸猿声啼不住\n轻舟已过万重山", note: "李白 · Li Bai", lang: "zh" },
  { label: "将进酒", text: "天生我材必有用\n千金散尽还复来", note: "李白 · Li Bai", lang: "zh" },
  { label: "赠汪伦", text: "桃花潭水深千尺\n不及汪伦送我情", note: "李白 · Li Bai", lang: "zh" },
  { label: "春望", text: "国破山河在\n城春草木深", note: "杜甫 · Du Fu", lang: "zh" },
  { label: "望岳", text: "会当凌绝顶\n一览众山小", note: "杜甫 · Du Fu", lang: "zh" },
  { label: "绝句", text: "两个黄鹂鸣翠柳\n一行白鹭上青天", note: "杜甫 · Du Fu", lang: "zh" },
  { label: "登高", text: "无边落木萧萧下\n不尽长江滚滚来", note: "杜甫 · Du Fu", lang: "zh" },
  { label: "悯农", text: "锄禾日当午\n汗滴禾下土", note: "李绅 · Li Shen", lang: "zh" },
  { label: "咏鹅", text: "鹅鹅鹅\n曲项向天歌", note: "骆宾王 · Luo Binwang", lang: "zh" },
  { label: "回乡偶书", text: "少小离家老大回\n乡音无改鬓毛衰", note: "贺知章 · He Zhizhang", lang: "zh" },
  { label: "咏柳", text: "不知细叶谁裁出\n二月春风似剪刀", note: "贺知章 · He Zhizhang", lang: "zh" },
  { label: "枫桥夜泊", text: "月落乌啼霜满天\n江枫渔火对愁眠", note: "张继 · Zhang Ji", lang: "zh" },
  { label: "江雪", text: "孤舟蓑笠翁\n独钓寒江雪", note: "柳宗元 · Liu Zongyuan", lang: "zh" },
  { label: "赋得古原草", text: "野火烧不尽\n春风吹又生", note: "白居易 · Bai Juyi", lang: "zh" },
  { label: "琵琶行", text: "同是天涯沦落人\n相逢何必曾相识", note: "白居易 · Bai Juyi", lang: "zh" },
  { label: "长恨歌", text: "在天愿作比翼鸟\n在地愿为连理枝", note: "白居易 · Bai Juyi", lang: "zh" },
  { label: "无题", text: "春蚕到死丝方尽\n蜡炬成灰泪始干", note: "李商隐 · Li Shangyin", lang: "zh" },
  { label: "锦瑟", text: "此情可待成追忆\n只是当时已惘然", note: "李商隐 · Li Shangyin", lang: "zh" },
  { label: "夜雨寄北", text: "何当共剪西窗烛\n却话巴山夜雨时", note: "李商隐 · Li Shangyin", lang: "zh" },
  { label: "山行", text: "停车坐爱枫林晚\n霜叶红于二月花", note: "杜牧 · Du Mu", lang: "zh" },
  { label: "泊秦淮", text: "商女不知亡国恨\n隔江犹唱后庭花", note: "杜牧 · Du Mu", lang: "zh" },
  { label: "登幽州台歌", text: "念天地之悠悠\n独怆然而涕下", note: "陈子昂 · Chen Zi'ang", lang: "zh" },
  { label: "凉州词", text: "羌笛何须怨杨柳\n春风不度玉门关", note: "王之涣 · Wang Zhihuan", lang: "zh" },
  { label: "出塞", text: "但使龙城飞将在\n不教胡马度阴山", note: "王昌龄 · Wang Changling", lang: "zh" },
  { label: "游子吟", text: "谁言寸草心\n报得三春晖", note: "孟郊 · Meng Jiao", lang: "zh" },
  { label: "水调歌头", text: "但愿人长久\n千里共婵娟", note: "苏轼 · Su Shi", lang: "zh" },
  { label: "题西林壁", text: "不识庐山真面目\n只缘身在此山中", note: "苏轼 · Su Shi", lang: "zh" },
  { label: "念奴娇", text: "大江东去\n浪淘尽千古风流人物", note: "苏轼 · Su Shi", lang: "zh" },
  { label: "定风波", text: "一蓑烟雨任平生", note: "苏轼 · Su Shi", lang: "zh" },
  { label: "虞美人", text: "问君能有几多愁\n恰似一江春水向东流", note: "李煜 · Li Yu", lang: "zh" },
  { label: "声声慢", text: "寻寻觅觅\n冷冷清清", note: "李清照 · Li Qingzhao", lang: "zh" },
  { label: "夏日绝句", text: "生当作人杰\n死亦为鬼雄", note: "李清照 · Li Qingzhao", lang: "zh" },
  { label: "满江红", text: "莫等闲\n白了少年头", note: "岳飞 · Yue Fei", lang: "zh" },
  { label: "游山西村", text: "山重水复疑无路\n柳暗花明又一村", note: "陆游 · Lu You", lang: "zh" },
  { label: "青玉案", text: "众里寻他千百度\n蓦然回首", note: "辛弃疾 · Xin Qiji", lang: "zh" },
  { label: "过零丁洋", text: "人生自古谁无死\n留取丹心照汗青", note: "文天祥 · Wen Tianxiang", lang: "zh" },
  { label: "石灰吟", text: "粉身碎骨浑不怕\n要留清白在人间", note: "于谦 · Yu Qian", lang: "zh" },
  { label: "竹石", text: "千磨万击还坚劲\n任尔东西南北风", note: "郑燮 · Zheng Xie", lang: "zh" },
  { label: "己亥杂诗", text: "落红不是无情物\n化作春泥更护花", note: "龚自珍 · Gong Zizhen", lang: "zh" },
  { label: "沁园春·雪", text: "北国风光\n千里冰封", note: "毛泽东 · Mao Zedong", lang: "zh" },
  { label: "再别康桥", text: "轻轻的我走了\n正如我轻轻的来", note: "徐志摩 · Xu Zhimo", lang: "zh" },
  { label: "断章", text: "你站在桥上看风景\n看风景的人在楼上看你", note: "卞之琳 · Bian Zhilin", lang: "zh" },
  { label: "面朝大海", text: "面朝大海\n春暖花开", note: "海子 · Hai Zi", lang: "zh" },
  { label: "一代人", text: "黑夜给了我黑色的眼睛\n我却用它寻找光明", note: "顾城 · Gu Cheng", lang: "zh" },

  // ——— English slogans ———
  { label: "Just do it", text: "just\ndo it", note: "Nike", lang: "en" },
  { label: "Think different", text: "think\ndifferent", note: "Apple", lang: "en" },
  { label: "Impossible is nothing", text: "impossible\nis nothing", note: "Adidas", lang: "en" },
  { label: "I'm lovin' it", text: "i'm\nlovin' it", note: "McDonald's", lang: "en" },
  { label: "Because you're worth it", text: "because you're\nworth it", note: "L'Oréal", lang: "en" },
  { label: "Open happiness", text: "open\nhappiness", note: "Coca-Cola", lang: "en" },
  { label: "Taste the feeling", text: "taste the\nfeeling", note: "Coca-Cola", lang: "en" },
  { label: "The happiest place", text: "the happiest\nplace on earth", note: "Disney", lang: "en" },
  { label: "Melts in your mouth", text: "melts in your mouth\nnot in your hands", note: "M&M's", lang: "en" },
  { label: "Have a break", text: "have a break\nhave a kit kat", note: "KitKat", lang: "en" },
  { label: "Finger lickin' good", text: "finger\nlickin' good", note: "KFC", lang: "en" },
  { label: "Eat fresh", text: "eat\nfresh", note: "Subway", lang: "en" },
  { label: "Betcha can't eat one", text: "betcha can't\neat just one", note: "Lay's", lang: "en" },
  { label: "Snap crackle pop", text: "snap!\ncrackle! pop!", note: "Rice Krispies", lang: "en" },
  { label: "Breakfast of champions", text: "breakfast of\nchampions", note: "Wheaties", lang: "en" },
  { label: "Got milk?", text: "got\nmilk?", note: "California Milk", lang: "en" },
  { label: "Red Bull gives you wings", text: "red bull gives\nyou wings", note: "Red Bull", lang: "en" },
  { label: "Priceless", text: "there are some things\nmoney can't buy", note: "Mastercard", lang: "en" },
  { label: "Don't leave home", text: "don't leave home\nwithout it", note: "Amex", lang: "en" },
  { label: "Like a good neighbor", text: "like a good neighbor\nstate farm is there", note: "State Farm", lang: "en" },
  { label: "Diamonds are forever", text: "a diamond\nis forever", note: "De Beers", lang: "en" },
  { label: "Because I'm worth the wait", text: "good things come\nto those who wait", note: "Guinness", lang: "en" },
  { label: "The ultimate driving machine", text: "the ultimate\ndriving machine", note: "BMW", lang: "en" },
  { label: "Vorsprung durch Technik", text: "vorsprung\ndurch technik", note: "Audi", lang: "en" },
  { label: "Think small", text: "think\nsmall", note: "Volkswagen", lang: "en" },
  { label: "Zoom zoom", text: "zoom\nzoom", note: "Mazda", lang: "en" },
  { label: "Let's go places", text: "let's go\nplaces", note: "Toyota", lang: "en" },
  { label: "Connecting people", text: "connecting\npeople", note: "Nokia", lang: "en" },
  { label: "Can you hear me now", text: "can you\nhear me now?", note: "Verizon", lang: "en" },
  { label: "Ideas for life", text: "ideas\nfor life", note: "Panasonic", lang: "en" },
  { label: "Make believe", text: "make\nbelieve", note: "Sony", lang: "en" },
  { label: "Inspire the next", text: "inspire\nthe next", note: "Hitachi", lang: "en" },
  { label: "Life's good", text: "life's\ngood", note: "LG", lang: "en" },
  { label: "Do the right thing", text: "do the\nright thing", note: "Spike Lee", lang: "en" },
  { label: "Don't be evil", text: "don't\nbe evil", note: "Google", lang: "en" },
  { label: "Move fast", text: "move fast\nbreak things", note: "startup lore", lang: "en" },
  { label: "Stay hungry", text: "stay hungry\nstay foolish", note: "Whole Earth Catalog", lang: "en" },
  { label: "Keep calm", text: "keep calm\nand carry on", note: "British WWII poster", lang: "en" },
  { label: "Yes we can", text: "yes\nwe can", note: "campaign slogan", lang: "en" },
  { label: "Live free", text: "live free\nor die", note: "New Hampshire", lang: "en" },
  { label: "Carpe diem", text: "carpe\ndiem", note: "Horace", lang: "en" },
  { label: "This too shall pass", text: "this too\nshall pass", note: "proverb", lang: "en" },
  { label: "Less is more", text: "less\nis more", note: "Mies van der Rohe", lang: "en" },
  { label: "Slow down", text: "slow\ndown", note: "latin practice", lang: "en" },
  { label: "Keep going", text: "keep\ngoing", note: "latin practice", lang: "en" },
  { label: "Begin again", text: "begin\nagain", note: "practice", lang: "en" },
  { label: "One day at a time", text: "one day\nat a time", note: "practice", lang: "en" },
  { label: "Breathe", text: "just\nbreathe", note: "practice", lang: "en" },
  { label: "Be here now", text: "be here\nnow", note: "Ram Dass", lang: "en" },
  { label: "Make it happen", text: "make it\nhappen", note: "practice", lang: "en" },
];


export const INKS: { label: string; value: string }[] = [
  { label: "Ink black", value: "#1b1a17" },
  { label: "Cinnabar", value: "#b4432c" },
  { label: "Indigo", value: "#2f4858" },
  { label: "Moss", value: "#5c6f4a" },
  { label: "Gold ochre", value: "#a97e35" },
  { label: "Plum", value: "#6b3f5e" },
];

export const PAPERS: { label: string; value: string; grid: string }[] = [
  { label: "Rice paper", value: "#f4efe4", grid: "#c9bda3" },
  { label: "Cream", value: "#faf7f0", grid: "#d8cfbd" },
  { label: "Slate", value: "#23272b", grid: "#4a5158" },
];
